### PR TITLE
31 kindtoticket

### PR DESCRIPTION
**Pull request by kevinprince**
Moving Kind to Ticket because attendees type changes per ticket. 

Event 1 they could be a sponsor
Event 2 they could be a attendee
Event 3 they could be crew. 

This change allows this level of flexibility.

### CODE REVIEW

**Comment by kevinprince** [comment]
Closes #31

**Comment by mseckington** [comment]
:+1: 

Although we should be using the expect syntax in rspec, rather than `should`, but we can change that all in one go later.

**Comment by kevinprince** [comment]
I'm just copying @cbetta 's example :D

**Comment by mseckington** [comment]
Yeah, I know. But he's doing it wrong :smirk:

:ok: for the rest

**Comment by cbetta** [comment]
I'm not wrong, just old. Syntax changed since I last wrote that :P

**Comment by kevinprince** [comment]
Opened an issue to handle this "mistake"

**Comment by cbetta** [comment]
:P

**Pull request merged**
